name: Build jupyterlab-mlops Image

on:
  pull_request:
    paths:
      - 'jupyterlab-mlops/**'

jobs:
  buildx-mlops:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [ "jupyter/pyspark-notebook:lab-3.2.1", "gcr.io/deeplearning-platform-release/base-cpu:m88" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx-mlops
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_DEPLOY_SA_KEY }}

      - name: Build jupyterlab-mlops
        uses: docker/build-push-action@v2
        with:
          context: jupyterlab-mlops
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: gcr.io/getindata-images-public/jupyterlab-mlops:dev
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
