name: Build Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build jupyterlab-mlops
        run: |
          docker pull gcr.io/getindata-images-public/jupyterlab-mlops:latest || true
          docker build --cache-from gcr.io/getindata-images-public/jupyterlab-mlops:latest --tag jupyterlab-mlops:latest jupyterlab-mlops
