name: Build & Publish Image

on:
  push:
    tags:
      - 'jupyterlab-mlops-*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set env
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          IMAGE_NAME=echo $TAG_NAME | sed -e's/\(.*\)-\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\)\+/\1/'
          VERSION=echo $TAG_NAME | sed -e's/\(.*\)-\([[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\)\+/\2/'
          echo $IMAGE_NAME
          echo $VERSION
